language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

 matrix:
  allow_failures:
    - php: 7
    - php: hhvm
  fast-finish: true

 before_script:
  # Get Composer up and running
  - travis_retry composer self-update
  - travis_retry composer install --perfer-dist --no-interaction --dev
  - travis_retry composer dump-autoload